### ISSUE TITLE
Handling offline stream

### ISSUE THREAD

**Issue by littlefyr** [flavioribeiro/clappr-rtmp-plugin#41]
Is it possible (if not, can it be made possible) to attach an event to clappr that fires when the RTMP stream starts sending and another event when the stream stops streaming.

I want to hide Clappr when the stream is offline and show a "Please Stand By" graphic/video loop. I've seen sample code that uses ajax to determine if the feed is active, but that only works when the stream is on the same domain and I'm not sure I can do that in this instance.

**Comment by gfronza** [comment]
Hi @littlefyr! sorry for the delayed reply.

I don't think there should be an event for that, because it goes beyond the player's role. But there are several ways you can accomplish that, using ajax or server sent events (or a combination of both) querying a server that holds the state of your broadcast. Another idea (that I'm not a huge fan of) would be to periodically attempt to start the playback of your streaming, and in case of a Clappr.Events.PLAYBACK_PLAY or Clappr.Events.PLAYER_ENDED you could show/hide the player.
