### ISSUE TITLE
How to fallback to another plugin?

### ISSUE THREAD

**Issue by DavidVentura** [flavioribeiro/clappr-rtmp-plugin#46]
I want to have playback primarily with rtmp, and in case of failure (mobiles) play hls. This is because live hls at this moment sucks for multiple reasons, so I'd rather use flash and only use hls when strictly necessary

**Comment by flavioribeiro** [comment]
I think you should keep all this logic outside clappr and embed it with the right source based on browser/environment

**Comment by gfronza** [comment]
@DavidVentura Clappr already support a list of sources instead of just one. On mobile devices, clappr will choose HLS over RTMP. But if you have more complicated business logic you will have to implement on your side, just like @flavioribeiro said. This is actually very simple, you just have to reorder your sources list in a way that your business rules are fulfilled (for example, if you know that your HLS stream sucks in Firefox 41 and Linux, then you leave your RTMP source at the beginning of your sources list).
